### ISSUE TITLE
Convert multiple tex files in the resources of the same maven project

### ISSUE THREAD

**Issue by vspiliop** [reallyinsane/mathan-latex-maven-plugin#9]
Hi Matthias,

I would like to have a few .tex files under the maven project resources and convert them to pdf. Just realised that you require to have exactly one. Any suggestions would be really appreciated.

 I use this plugin (together with others, e.g., a Plantuml one) to generate during build time diagrams and latex artefacts (mainly tables) for including them in the generate maven site documentation of the repo.

Thanks for your time!

**Comment by reallyinsane** [comment]
Hi Vassilis,

yes, the idea was to use the plugin to create a single document. This can consist of many tex files but for all steps executed a reference to a single file is needed, at this time.

You could achive this using multiple executions in the pom.xml. So instead of

```
<configuration>
  <texFile>main.tex</texFile>
</configuration>
```
you could use this:

```
<executions>
  <execution>
    <id>one</id>
    <configuration>
      <texFile>first.tex</texFile>
    </configuration>
  </execution>
  <execution>
    <id>two</id>
    <configuration>
      <texFile>second.tex</texFile>
    </configuration>
  </execution>
```

Hope this helps.

Regards,

Matthias
